### PR TITLE
more on issue #3

### PR DESCRIPTION
**Pull request by elasticguru**

### CODE REVIEW

**Comment by elasticguru** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **elasticguru**

If they are not already assigned, you can assign the PR to them by writing `/assign @elasticguru` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=elasticguru%2Ftest-spring-app1).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/elasticguru/test-spring-app1/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by elasticguru** [comment]
:star: PR built and available in a preview environment **elasticguru-test-spring-app1-pr-4** [here](http://test-spring-app1.cd-elasticguru-test-spring-app1-pr-4.app.ekube.io)

**Comment by berahac** [comment]
/approve_____________________________ Cristian Beraha - ICP-AC/ICP-AP/ICP-FDO cristian.beraha@e.lastic.guru eLasticGuru P: +1 954 201-8049 / +54 348 421-8013 M: + 54 911 3350-8422---- On Wed, 10 Jul 2019 20:48:33 -0300  notifications@github.com<notifications@github.com> wrote ----[APPROVALNOTIFIER] This PR is NOT APPROVED 
This pull-request has been approved by: 
To fully approve this pull request, please assign additional approvers. 
We suggest the following additional approver: elasticguru 
If they are not already assigned, you can assign the PR to them by writing /assign @elasticguru in a comment when ready. 
The full list of commands accepted by this bot can be found here. 
The pull request process is described here 
 
Needs approval from an approver in each of these files: 
 
OWNERS 
 
Approvers can indicate their approval by writing /approve in a comment 
Approvers can cancel approval by writing /approve cancel in a comment

**Comment by berahac** [comment]
/approve




_____________________________

 Cristian Beraha - ICP-AC/ICP-AP/ICP-FDO

 cristian.beraha@e.lastic.guru

 eLasticGuru

 P:+54 348 421-8013

 M: + 54 911 3350-8422


---- On Wed, 10 Jul 2019 20:48:33 -0300 notifications@github.com wrote ----



[APPROVALNOTIFIER] This PR is NOT APPROVED

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: elasticguru

If they are not already assigned, you can assign the PR to them by writing /assign @elasticguru in a comment when ready.

The full list of commands accepted by this bot can be found here.

The pull request process is described here

Needs approval from an approver in each of these files:
OWNERS

Approvers can indicate their approval by writing /approve in a comment
Approvers can cancel approval by writing /approve cancel in a comment

**Comment by elasticguru** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/elasticguru/test-spring-app1/pull/4#issuecomment-510272724" title="Approved">berahac</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=elasticguru%2Ftest-spring-app1).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/elasticguru/test-spring-app1/blob/master/OWNERS)~~ [berahac]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
